config/routes.rb
Black::Application.routes.draw do

get "staticpages/index"
match '/contact' => 'staticpages#contact'
match '/events' => 'staticpages#events'
match '/index' => 'staticpages#index'

  root :to => 'staticpages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/emailer_controller.rb
class EmailerController < ApplicationController
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	def index
	end
	def contact
	end
	def events
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emailer_helper.rb
module EmailerHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Black</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<center> <h1> Black and Gold Cafe </h1>
		Hours: Monday - Thursday 7 Am to 8pm, Friday - Saturday 7 AM to Midnight, Sunday 11 to 8 pm <br><br>
<%= link_to "index", index_path %> , <%= link_to "contact us", contact_path %> ,  <%= link_to "events", events_path %></center>
<%= yield %>
<br> <br>
<center>
	Black and Gold Cafe <br> 414 Williamston Road <br> Anderson SC 29627 <br> Tel: 864 XXX XXXX
</center>
</body>
</html>

app/views/staticpages/contact.html.erb
Contact

app/views/staticpages/events.html.erb
Events

app/views/staticpages/index.html.erb
Index page
<br> <br> 
<center>
<h2> Drinks </h2> </center>
<div id="list">
Coffee ......................................................... Regular $1.25 / Large $1.75<br>
Espressso ...................................................... Single $1.25 / Double $1.95<br>
Cappuccino ..................................................... Regular $2.45 / Large $3.45 <br>
Latte .......................................................... Regular $2.25 / Large $3.25 <br>
Iced Coffee .................................................... Regular $1.50 / large $2 <br>
Frap ........................................................... Regular $2.85 / Large $3.85 <br>
Tea  ........................................................... Regular $1.25 / Large $1.75<br>
Flavor Shots (Vanilla, Hazelnut, Butter Pecan, Mocha, Caramel).. $0.45 ea <br>
Bottled Water .................................................. $1 <br>
Monster Energy ................................................. $3 <br>
Red Bull ....................................................... $3.50 <br>
Yohoo .......................................................... $1.75<br>
16 oz Soda ..................................................... $1.50<br>
5 Hour Energy .................................................. $2.95<br>
Smoothies (Banana, Strawberry, Mango) .......................... $3.50<br>
Protein Shot ................................................... $0.50 ea<br>
Shakes (Vanilla, Chololate, Strawberry)......................... $3.75<br>
Floats (Coke, Diet Coke, Rootbeer).............................. $2.75<br>
</div>

<h2> Breakfast </h2>
</center><div id="list">
Muffins (varies daily) ......................................... Small $1.75 / Large $3.25<br>
Apple Fritters ................................................. $2.65 ea<br>
Cake Donuts (powdered, chocolate or coffee cake)................ $1.75 ea <br>
Mini Donuts (powdered or chocolate) ............................ $1.75 for 8 <br>
Pastries (assorted) ............................................ $2.25 <br>
Hashbrowns ..................................................... $1.50 for two<br>
Tater Tots ..................................................... $1.50 <br>
</div>

<center> <h2> Snacks </h2></center><div id="list">
Chicken Nuggets ................................................ 5 pc $1.25 / 10 pc $2.25 <br> 
Mozarella Sticks ............................................... 6 pc $2.25 <br>
Onion Rings .................................................... $2.25 <br>
Popcorn ........................................................ Small $1.50 / Large $2.50<br>
Hot Dog ........................................................ $1.50 <br>
Corn Dog ....................................................... $1.75 <br>
Nachos ......................................................... Small $1.50 / Large $2.75<br>
Fries .......................................................... Small $1.35 / Large $2.50 <br>
Add Chili ...................................................... $0.45<br>
Add Cheeze ..................................................... $0.45 <br>
Add Pimento Cheeze ............................................. $0.55<br>
Add Pork ....................................................... $0.85 <br>

</div>

<h2> Desserts </h2><div id="list">
Pie (varies) ................................................... $2.45 per slice <br>
Cheesecake (plain, strawberry, caramel, chocolate) ............. $2.95 per slice <br>
Pudding (vanilla/chocolate) .................................... $1.25 <br>
Ice Cream Sundae (caramel, strawberry, chocolate) .............. $1.95 <br>
Cookie ......................................................... $1 <br>
Pastries (varies) .............................................. $2.95 per <br>



</div>